# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

output_directory = './fastlane/Test Output/'
coverage_directory = '/coverage'

default_platform(:android)

platform :android do

  desc "Assemble build"
  lane :assemble do
    gradle(
      tasks: ["assembleDebug", "assembleDebugAndroidTest", ":security::assembleDebugAndroidTest"]
    )
  end
  
  desc "Runs all the tests with coverage"
  lane :unit_tests do
    gradle(
      tasks: ["jacocoTestReport", ":verify:jacocoCoverageVerification"]
    )
  end

  desc "Size impact report"
  lane :sdk_sizer do
    gradle(
      task: "generateSizeReport"
    )
  end

  desc "Check android, kotlin and java style convention"
  lane :lint_checker do
    gradle(
      tasks: ["ktlint", ":verify:lint", ":security:lint", "spotlessCheck"]
    )
  end
end
