@startuml TwilioVerifySDK
interface TwilioVerify {
    createFactor(factorInput: FactorInput, success: (Factor) -> (), error: (TwilioVerifyException)->())
    verifyFactor(verifyFactorInput: VerifyFactorInput, success: (Factor) -> (), error: (TwilioVerifyException)->())
    getChallenge(challengeSid: String, success: (Challenge) -> (), error: (TwilioVerifyException)->())
    verifyChallenge(challenge: Challenge, success: (Challenge) -> (), error: (TwilioVerifyException)->())
}
class TwilioVerify.Builder {
         authorization: Authorization
         context: Context
         networkProvider: NetworkProvider
         build(): TwilioVerify
    }
class Domain.TwilioVerifyManager implements TwilioVerify {
    
}
class Domain.Factor.FactorFacade {
    createFactor(factorInput: FactorInput, success: (Factor) -> (), error: (TwilioVerifyException)->())
    verifyFactor(verifyFactorInput: VerifyFactorInput, success: (Factor) -> (), error: (TwilioVerifyException)->())
}
interface FactorInput {
    friendlyName: String
}
class PushFactorInput implements FactorInput {
    pushToken: String
    jwt: String
}
interface VerifyFactorInput {
    sid: String
}

class VerifyPushFactorInput implements VerifyFactorInput {
    
}

class TwilioVerifyException extends Exception {
    cause: Exception
    errorCode: ErrorCode
}
enum TwilioVerifyException.ErrorCodes {
        NetworkError
    }
class NetworkException {
    statusCode: Int
    errorBody: String?
}
Domain.TwilioVerifyManager o-left-> Domain.Factor.FactorFacade: create factor
Domain.Factor.FactorFacade o-left-> Domain.Factor.PushFactory: create push factor
@enduml