/*
 * Copyright (c) 2020, Twilio Inc.
 */
package com.twilio.verify.models

/**
 * Describes the information required to create a Factor which type is Push
 *
 * @property friendlyName: Friendly name of the factor, you can use this for display purposes
 * @property serviceSid: Service id
 * @property identity: Identifies the user, should be an UUID you should not use PII (Personal Identifiable Information)
 * because the systems that will process this attribute assume it is not directly identifying information
 * @property pushToken: Registration token generated by the FCM SDK on initial startup of your app
 * @property accessToken: Previously generated Access Token using the /accessTokens endpoint
 * @property factorType: Type of the factor
 */
class PushFactorPayload(
  override val friendlyName: String,
  override val serviceSid: String,
  override val identity: String,
  val pushToken: String,
  val accessToken: String
) : FactorPayload {
  override val factorType: FactorType
    get() = FactorType.PUSH
}