package com.twilio.verify.models

/*
 * Copyright (c) 2020, Twilio Inc.
 */

/**
 * Describes the information required to update a **Factor** which type is **Push**
 */
data class UpdatePushFactorPayload(
  /**
   * Factor sid
   */
  override val sid: String,
  /**
   * Registration token generated by the FCM SDK on initial startup of your app
   */
  val pushToken: String
) : UpdateFactorPayload